

export const replaceTextWithManaSymbols = (text) => {
    // Example: Replace mana codes with symbols using a simple string replacement
    return text.replace(/{R}/g, '<i class="ms ms-r ms-cost ms-shadow"></i>')  
               .replace(/{G}/g, '<i class="ms ms-g ms-cost ms-shadow"></i>') 
               .replace(/{U}/g, '<i class="ms ms-u ms-cost ms-shadow"></i>') 
               .replace(/{W}/g, '<i class="ms ms-w ms-cost ms-shadow"></i>')
               .replace(/{B}/g, '<i class="ms ms-b ms-cost ms-shadow"></i>')
               .replace(/\{0\}/g, '<i class="ms ms-0 ms-cost ms-shadow"></i>')
               .replace(/\{1\}/g, '<i class="ms ms-1 ms-cost ms-shadow"></i>')
               .replace(/\{2\}/g, '<i class="ms ms-2 ms-cost ms-shadow"></i>')
               .replace(/\{3\}/g, '<i class="ms ms-3 ms-cost ms-shadow"></i>')
               .replace(/\{4\}/g, '<i class="ms ms-4 ms-cost ms-shadow"></i>')
               .replace(/\{5\}/g, '<i class="ms ms-5 ms-cost ms-shadow"></i>')
               .replace(/\{6\}/g, '<i class="ms ms-6 ms-cost ms-shadow"></i>')
               .replace(/\{7\}/g, '<i class="ms ms-7 ms-cost ms-shadow"></i>')
               .replace(/\{8\}/g, '<i class="ms ms-8 ms-cost ms-shadow"></i>')
               .replace(/\{9\}/g, '<i class="ms ms-9 ms-cost ms-shadow"></i>')
               .replace(/\{10\}/g, '<i class="ms ms-10 ms-cost ms-shadow"></i>')
               .replace(/\{11\}/g, '<i class="ms ms-11 ms-cost ms-shadow"></i>')
               .replace(/\{12\}/g, '<i class="ms ms-12 ms-cost ms-shadow"></i>')
               .replace(/\{13\}/g, '<i class="ms ms-13 ms-cost ms-shadow"></i>')
               .replace(/\{14\}/g, '<i class="ms ms-14 ms-cost ms-shadow"></i>')
               .replace(/\{15\}/g, '<i class="ms ms-15 ms-cost ms-shadow"></i>')
               .replace(/\{16\}/g, '<i class="ms ms-16 ms-cost ms-shadow"></i>')
               .replace(/\{17\}/g, '<i class="ms ms-17 ms-cost ms-shadow"></i>')
               .replace(/\{18\}/g, '<i class="ms ms-18 ms-cost ms-shadow"></i>')
               .replace(/\{19\}/g, '<i class="ms ms-19 ms-cost ms-shadow"></i>')
               .replace(/\{20\}/g, '<i class="ms ms-20 ms-cost ms-shadow"></i>')
};
