

export const replaceTextWithManaSymbols = (text) => {
    // Example: Replace mana codes with symbols using a simple string replacement
    return text.replace(/{R}/g, '<i class="ms ms-r ms-cost ms-shadow"></i>')  
               .replace(/{G}/g, '<i class="ms ms-g ms-cost ms-shadow"></i>') 
               .replace(/{U}/g, '<i class="ms ms-u ms-cost ms-shadow"></i>') 
               .replace(/{W}/g, '<i class="ms ms-w ms-cost ms-shadow"></i>')
               .replace(/{B}/g, '<i class="ms ms-b ms-cost ms-shadow"></i>')
               .replace(/{R\/P}/g, '<i class="ms ms-rp ms-cost ms-shadow"></i>')
               .replace(/{G\/P}/g, '<i class="ms ms-gp ms-cost ms-shadow"></i>')
               .replace(/{U\/P}/g, '<i class="ms ms-up ms-cost ms-shadow"></i>')
               .replace(/{W\/P}/g, '<i class="ms ms-wp ms-cost ms-shadow"></i>')
               .replace(/{B\/P}/g, '<i class="ms ms-bp ms-cost ms-shadow"></i>')
               .replace(/\{0\}/g, '<i class="ms ms-0 ms-cost ms-shadow"></i>')
               .replace(/\{1\}/g, '<i class="ms ms-1 ms-cost ms-shadow"></i>')
               .replace(/\{2\}/g, '<i class="ms ms-2 ms-cost ms-shadow"></i>')
               .replace(/\{3\}/g, '<i class="ms ms-3 ms-cost ms-shadow"></i>')
               .replace(/\{4\}/g, '<i class="ms ms-4 ms-cost ms-shadow"></i>')
               .replace(/\{5\}/g, '<i class="ms ms-5 ms-cost ms-shadow"></i>')
               .replace(/\{6\}/g, '<i class="ms ms-6 ms-cost ms-shadow"></i>')
               .replace(/\{7\}/g, '<i class="ms ms-7 ms-cost ms-shadow"></i>')
               .replace(/\{8\}/g, '<i class="ms ms-8 ms-cost ms-shadow"></i>')
               .replace(/\{9\}/g, '<i class="ms ms-9 ms-cost ms-shadow"></i>')
               .replace(/\{10\}/g, '<i class="ms ms-10 ms-cost ms-shadow"></i>')
               .replace(/\{11\}/g, '<i class="ms ms-11 ms-cost ms-shadow"></i>')
               .replace(/\{12\}/g, '<i class="ms ms-12 ms-cost ms-shadow"></i>')
               .replace(/\{13\}/g, '<i class="ms ms-13 ms-cost ms-shadow"></i>')
               .replace(/\{14\}/g, '<i class="ms ms-14 ms-cost ms-shadow"></i>')
               .replace(/\{15\}/g, '<i class="ms ms-15 ms-cost ms-shadow"></i>')
               .replace(/\{16\}/g, '<i class="ms ms-16 ms-cost ms-shadow"></i>')
               .replace(/\{17\}/g, '<i class="ms ms-17 ms-cost ms-shadow"></i>')
               .replace(/\{18\}/g, '<i class="ms ms-18 ms-cost ms-shadow"></i>')
               .replace(/\{19\}/g, '<i class="ms ms-19 ms-cost ms-shadow"></i>')
               .replace(/\{20\}/g, '<i class="ms ms-20 ms-cost ms-shadow"></i>')
               .replace(/{W\/U}/g, '<i class="ms ms-wu ms-cost ms-shadow"></i>')
               .replace(/{W\/B}/g, '<i class="ms ms-wb ms-cost ms-shadow"></i>')
               .replace(/{U\/B}/g, '<i class="ms ms-ub ms-cost ms-shadow"></i>')
               .replace(/{U\/R}/g, '<i class="ms ms-ur ms-cost ms-shadow"></i>')
               .replace(/{B\/R}/g, '<i class="ms ms-br ms-cost ms-shadow"></i>')
               .replace(/{B\/G}/g, '<i class="ms ms-bg ms-cost ms-shadow"></i>')
               .replace(/{R\/W}/g, '<i class="ms ms-rw ms-cost ms-shadow"></i>')
               .replace(/{R\/G}/g, '<i class="ms ms-rg ms-cost ms-shadow"></i>')
               .replace(/{G\/W}/g, '<i class="ms ms-gw ms-cost ms-shadow"></i>')
               .replace(/{W\/U\/P}/g, '<i class="ms ms-wup ms-cost ms-shadow"></i>')
               .replace(/{W\/B\/P}/g, '<i class="ms ms-wbp ms-cost ms-shadow"></i>')
               .replace(/{U\/B\/P}/g, '<i class="ms ms-ubp ms-cost ms-shadow"></i>')
               .replace(/{U\/R\/P}/g, '<i class="ms ms-urp ms-cost ms-shadow"></i>')
               .replace(/{B\/R\/P}/g, '<i class="ms ms-brp ms-cost ms-shadow"></i>')
               .replace(/{B\/G\/P}/g, '<i class="ms ms-bgp ms-cost ms-shadow"></i>')
               .replace(/{R\/W\/P}/g, '<i class="ms ms-rwp ms-cost ms-shadow"></i>')
               .replace(/{R\/G\/P}/g, '<i class="ms ms-rgp ms-cost ms-shadow"></i>')
               .replace(/{G\/W\/P}/g, '<i class="ms ms-gwp ms-cost ms-shadow"></i>')
               .replace(/{G\/U\/P}/g, '<i class="ms ms-gup ms-cost ms-shadow"></i>')
               .replace(/{T}/g, '<i class="ms ms-tap ms-cost ms-shadow"></i>')
               .replace(/{Q}/g, '<i class="ms ms-untap ms-cost"></i>')
               .replace(/{CHAOS}/g, '<i class="ms ms-chaos"></i>')
};
